modLoader = "javafml"
loaderVersion = "[33,35)"
issueTrackerURL = "https://github.com/MinerArcana/Transfiguration/issues"
license="MIT"

[[mods]]
    modId = "transfiguration"
    version = "${file.jarVersion}"
    displayName = "Transfiguration"
    authors = "SkySom, DivineAspect"
    description = '''
        '''

[[dependencies.transfiguration]]
    modId = "forge"
    mandatory = true
    versionRange = "[33.0.0,35.0.0)"
    ordering = "NONE"
    side = "BOTH"