modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/MinerArcana/Transfiguration/issues"
license="MIT"

[[mods]]
    modId = "transfiguration"
    version = "${file.jarVersion}"
    displayName = "Transfiguration"
    authors = "SkySom, DivineAspect"
    description = '''
        '''

[[dependencies.transfiguration]]
    modId = "forge"
    mandatory = true
    versionRange = "[40,41)"
    ordering = "NONE"
    side = "BOTH"