modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/MinerArcana/Transfiguration/issues"

[[mods]]
    modId = "transfiguration"
    version = "${file.jarVersion}"
    displayName = "Transfiguration"
    authors = "SkySom, DivineAspect"
    description = '''
        '''

[[dependencies.transfiguration]]
    modId = "forge"
    mandatory = true
    versionRange = "[32.0.68,)"
    ordering = "NONE"
    side = "BOTH"